### ISSUE TITLE
replace rplos

### ISSUE THREAD

**Issue by jeanetteclark** [DataONEorg/scythe#39]
rplos got pulled from cran and archived so we need to find a replacement for it, or just refactor the code to remove the dep on the package.

**Comment by mbjones** [comment]
Alternatively, move it to `Suggests` and conditionally check if it is installed before running code that depends on it. This is common strategy for supporting multiple services for which the needed packages may or may not be available. Works particularly if rplos is still on github and installable, just not meeting CRAN requirements. Also, add a new `Remotes:` section to the description, so that it can be installed automatically with `remotes::install_deps()`, as described here: https://remotes.r-lib.org/articles/dependencies.html
